// export const BASE_PATH = "http://localhost:5000";
export const BASE_PATH = 'https://vocab-quiz-backend.herokuapp.com';
export const API_LOGIN = `${BASE_PATH}/login`;
export const API_SIGNUP = `${BASE_PATH}/signup`;
export const API_RESET_PASSWORD = `${BASE_PATH}/reset-password`;
export const API_SELF = `${BASE_PATH}/self`;
export const API_WORDS = `${BASE_PATH}/words`;
export const API_WORDS_COUNT = `${BASE_PATH}/words/count`;
export const API_BOOKMARKED = `${BASE_PATH}/bookmarked`;
